name: zubora_calorie
description: カロリー管理アプリ「ずぼらカロリー」

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  flutter_bloc: ^8.0.0
  sqflite: ^2.0.0
  path: ^1.8.0
  fl_chart: ^0.55.0
  intl: ^0.18.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  shared_preferences: ^2.0.0
  connectivity_plus: ^4.0.0
  path_provider: ^2.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/
